name: Deploy main doc
on:
  workflow_dispatch:
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  #  release_v4:
  #    if: ${{ always() }}
  #    uses: zyfra/Prizm/.github/workflows/main-publish-ng17.yml@main
  #    secrets: inherit
  release_v3:
    needs: release_v4
    if: ${{ always() }}
    uses: zyfra/Prizm/.github/workflows/deploy-main-doc-ng16.yml@main
    secrets: inherit

  release_v2:
    needs: release_v3
    if: ${{ always() }}
    uses: zyfra/Prizm/.github/workflows/deploy-main-doc-ng15.yml@main
    secrets: inherit

  release_v1:
    needs: release_v2
    uses: zyfra/Prizm/.github/workflows/deploy-main-doc-ng13.yml@main
    secrets: inherit
