name: Install dependencies

on:
  workflow_call:
    inputs:
      with_cache:
        default: true
        type: boolean
      angular_version:
        default: 16
        type: number

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    env:
      PACKAGE_JSON: ./package.json.ng${{ inputs.angular_version }}
      PACKAGE_LOCK_JSON: ./package-lock.json.ng${{ inputs.angular_version }}
    steps:
      - name: Restore cache
        id: cache-restore
        if: ${{ inputs.with_cache }}
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules_ng_${{ inputs.angular_version }}-${{ hashFiles(env.PACKAGE_LOCK_JSON) }}
          restore-keys: |
            ${{ runner.os }}-node_modules_ng_${{ inputs.angular_version }}-

      - name: 'Initial changes'
        run: |
          cp -f ${{ env.PACKAGE_JSON }} ./package.json
          cp -f ${{ env.PACKAGE_LOCK_JSON }} ./package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v3
        if: ${{ inputs.with_cache && steps.cache-restore.outputs.cache-hit != 'true' && always() }}
        with:
          path: ./node_modules
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
