name: Testing

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
        angular: [14, 15, 16]
    uses: ./.github/workflows/workflow.yml
    with:
      node_version: ${{ matrix.node }}
      angular_version: ${{ matrix.angular }}
