name: Pre-released
on:
  release:
    types:
      - prereleased
  workflow_dispatch:
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  pre_release_v4:
    if: ${{ always() }}
    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng17.yml@main
    secrets: inherit
#  pre_release_v3:
#    if: ${{ always() }}
#    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng16.yml@main
#    secrets: inherit
#
#  pre_release_v2:
#    needs: pre_release_v3
#    if: ${{ always() }}
#    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng15.yml@main
#    secrets: inherit
#
#  pre_release_v1:
#    needs: pre_release_v1
#    if: ${{ always() }}
#    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng14.yml@main
#    secrets: inherit
