name: Released
on:
  release:
    types:
      - released
  workflow_dispatch:
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  release_v4:
    if: ${{ startsWith(github.event.release.tag_name, '4') }}
    uses: zyfra/Prizm/.github/workflows/main-publish-ng17.yml@main
    secrets: inherit

  release_v3:
    if: ${{ startsWith(github.event.release.tag_name, '3') }}
    uses: zyfra/Prizm/.github/workflows/main-publish-ng16.yml@main
    secrets: inherit

  release_v2:
    if: ${{ startsWith(github.event.release.tag_name, '2') }}
    uses: zyfra/Prizm/.github/workflows/main-publish-ng15.yml@main
    secrets: inherit

  release_v1:
    if: ${{ startsWith(github.event.release.tag_name, '1') }}
    uses: zyfra/Prizm/.github/workflows/main-publish-ng14.yml@main
    secrets: inherit
